#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILES=$( cd $DIR/.. && pwd )

if [[ ! -f ~/.gitconfig ]]; then
  ln -s $DOTFILES/.gitconfig ~/.gitconfig
  ln -s $DOTFILES/.gitignore_global ~/.gitignore_global
  git config --global core.excludesfile ~/.gitignore_global
fi
